#!/usr/bin/env bash
#  Configure your Nginx server to have a custom 404 page that contains 
#  the string Ceci n'est pas une page.
#  Requirements:
#  The page must return an HTTP 404 error code
#  The page must contain the string Ceci n'est pas une page
#  Using what you did with 3-redirection, write 4-not_found_page_404 
#!/usr/bin/env bash
#  Configure your Nginx server to have a custom 404 page that contains 
#  the string Ceci n'est pas une page.
#  Requirements:
#  The page must return an HTTP 404 error code
#  The page must contain the string Ceci n'est pas une page
#  Using what you did with 3-redirection, write 4-not_found_page_404 
#  so that it configures a brand new Ubuntu machine to the requirements 
#  asked in this task
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

new_str="\\\trewrite ^/redirect_me https://www.linkedin.com/in/isa-lawal;"
sudo sed -i "42i $new_str" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404

new_str="\\\terror_page 404 /error404;"
sudo sed -i "43i $new_str" /etc/nginx/sites-available/default

sudo service nginx restart
